# Generated by Django 3.2.5 on 2021-07-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('tracking_item_id', models.CharField(max_length=8)),
                ('tracking_item_name', models.TextField()),
                ('data_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('tracking_item_id', models.CharField(max_length=8)),
                ('tracking_value', models.TextField()),
                ('tracking_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.tracking_items')),
            ],
        ),
    ]
