# Generated by Django 3.2.5 on 2021-07-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trackers',
            new_name='Tracker',
        ),
        migrations.RenameModel(
            old_name='Tracking_items',
            new_name='Tracking_item',
        ),
    ]
